services:
  - type: web
    name: traffic-violation-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    repo: 
    branch: main
    envVars:
      - key: API_USER
        value: admin
      - key: API_PASS
        value: admin123
      - key: MODEL_PATH
        value: /app/models/yolov8n.pt
      - key: MAX_UPLOAD_MB
        value: "50"
